#For Exceeds Expecations
module Grade
  MEETS_EXPECTATIONS = 2
  EXCEEDS_EXPECTATIONS = 3
  DOES_NOT_MEET_EXPECTATIONS = 0
  MAKEUP_POINT = 1

  GRADES = [
    DOES_NOT_MEET_EXPECTATIONS,
    MAKEUP_POINT,
    MEETS_EXPECTATIONS,
    EXCEEDS_EXPECTATIONS
  ]
end
