---
title: "Dog Directions"
type: "exercise"
description: "Follow along while making a recipe using React stateful components"
tags: "javascript, react, stateful components"
behaviors:
  - sinatra
  - react_on_node
ignore:
- "node_modules/"
- "dog-directions.md"
