---
title: "Geometric Classes"
type: "challenge"
description: "Create Ruby objects for different shapes."
behaviors:
  - ruby_and_rspec
ignore:
- "geometric-classes.md"
- ".rspec"
- "Gemfile"
- "Gemfile.lock"
- "Rakefile"
