# Configure the database used when in the development environment
development:
  adapter: postgresql
  encoding: unicode
  database: star_fleet_development
  pool: 20
  username:
  password:

# Configure the database used when in the test environment
test:
  adapter: postgresql
  encoding: unicode
  database: star_fleet_test
  pool: 20
  username:
  password:
