# Please change the name of this lesson (and, then, delete this comment).
# All of the following should have the same name
#   - The lesson folder.
#   - The lesson markdown file, and the ignored file, below.
#   - The title, below.
---
title: "React Router Exercise with useState"
type: "exercise"  # challenge, exercise, article, video
description: "React Router Exercise."
tags: "react"
behaviors:
  - react_on_node
  - react_router
  - sinatra
ignore:
- "react-router-exercise-usestate.md"
