---
title: "Database Relationships"
type: "article"
description: "Describes how relationships between information can be structured in a relational database."
tags: "databases, data-normalization, sql"
