---
title: "HTTP POST and HTML Forms"
type: "article"
description: "Describes how users can submit data back to our web apps using HTML forms."
behaviors:
  - sinatra
tags: "html, html-forms, http, http-post"
