---
title: "Dark Nebula ES6"
type: "challenge"
description: >
  Travel deeper into the dark corners of JavaScript.
tags: "javascript, tdd"
ignore:
- "data/"
- "lib/"
- "node_modules/"
- "tests/"
- ".jshintrc"
- "CHANGELOG.md"
- "nebula-part-es6.md"
- "Gruntfile.js"
- "help.txt"
- "index.js"
- "package.json"
