let data = [
  {
    id: 166543,
    name: 'monkey_party',
    full_name: 'LaunchAcademy/monkey_party',
    private: false,
    description: 'MailChimp functionality for those who like tests and HTTParty',
    fork: false,
    url: 'https://api.github.com/repos/LaunchAcademy/monkey_party',
    created_at: '2009-04-02T20:38:01Z',
    updated_at: '2016-05-09T09:39:24Z',
    size: 188,
    stargazers_count: 4,
    watchers_count: 4,
    language: 'Ruby',
    default_branch: 'master',
    gravatar_id: '',
    site_admin: false,
    license:
      {
        id: 'mit',
        url: 'https://api.github.com/licenses/mit'
      },
    owner_url: 'https://api.github.com/users/LaunchAcademy',
    owner: 'LaunchAcademy',
    owner_type: 'Organization'
  },
  {
    id: 284534,
    name: 'booster',
    full_name: 'LaunchAcademy/booster',
    private: false,
    description: 'Rails Template',
    fork: false,
    url: 'https://api.github.com/repos/LaunchAcademy/booster',
    created_at: '2009-08-21T20:40:20Z',
    updated_at: '2015-02-03T09:43:03Z',
    size: 454,
    stargazers_count: 44,
    watchers_count: 44,
    language: 'Ruby',
    default_branch: 'master',
    gravatar_id: '',
    site_admin: false,
    owner_url: 'https://api.github.com/users/LaunchAcademy',
    owner:
      {
        login: 'LaunchAcademy',
        type: 'Organization',
        permissions: {
          admin: false
        }
      },
    owner_type: 'Organization'
  },
  {
    id: 4097959,
    name: 'roboto',
    full_name: 'LaunchAcademy/roboto',
    private: false,
    description: 'Environment specific robots.txt for your Rails Apps',
    fork: false,
    url: 'https://api.github.com/repos/LaunchAcademy/roboto',
    created_at: '2012-04-21T17:24:44Z',
    updated_at: '2017-02-20T01:58:22Z',
    size: 199,
    stargazers_count: 72,
    watchers_count: 72,
    language: 'Ruby',
    default_branch: 'master',
    gravatar_id: '',
    site_admin: false,
    owner_url: 'https://api.github.com/users/LaunchAcademy',
    owner: 'LaunchAcademy',
    owner_type: 'Organization'
  },
  {
    id: 9680485,
    name: 'shopping_list',
    full_name: 'LaunchAcademy/shopping_list',
    private: false,
    description: 'git it?',
    fork: false,
    url: 'https://api.github.com/repos/LaunchAcademy/shopping_list',
    created_at: '2013-04-25T20:18:39Z',
    updated_at: '2014-03-05T15:52:32Z',
    size: 218,
    stargazers_count: 0,
    watchers_count: 0,
    language: null,
    default_branch: 'master',
    gravatar_id: '',
    site_admin: false,
    owner_url: 'https://api.github.com/users/LaunchAcademy',
    owner: 'LaunchAcademy',
    owner_type: 'Organization'
  },
  {
    id: 9986615,
    name: 'invalid_html_exercise',
    full_name: 'LaunchAcademy/invalid_html_exercise',
    private: false,
    description: 'The root page of this application has some HTML validation errors. Clone this repo and see if you can fix them. More instructions inside Apollo under the Tools section.',
    fork: false,
    url: 'https://api.github.com/repos/LaunchAcademy/invalid_html_exercise',
    created_at: '2013-05-10T17:33:19Z',
    updated_at: '2014-03-01T11:01:15Z',
    size: 139,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'Ruby',
    default_branch: 'master',
    gravatar_id: '',
    site_admin: false,
    owner_url: 'https://api.github.com/users/LaunchAcademy',
    owner: 'LaunchAcademy',
    owner_type: 'Organization'
  },
  {
    id: 10065962,
    name: 'cathubdoghubmadebyjason',
    full_name: 'LaunchAcademy/cathubdoghubmadebyjason',
    private: false,
    description: 'cathub_doghub',
    fork: false,
    url: 'https://api.github.com/repos/LaunchAcademy/cathubdoghubmadebyjason',
    created_at: '2013-05-14T22:07:01Z',
    updated_at: '2014-01-01T04:09:12Z',
    size: 158,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'Ruby',
    default_branch: 'master',
    gravatar_id: '',
    site_admin: false,
    owner_url: 'https://api.github.com/users/LaunchAcademy',
    owner: 'LaunchAcademy',
    owner_type: 'Organization'
  },
  {
    id: 10068366,
    name: 'ruby_koans',
    full_name: 'LaunchAcademy/ruby_koans',
    private: false,
    description: 'A set of Koans to teach the Ruby language',
    fork: true,
    url: 'https://api.github.com/repos/LaunchAcademy/ruby_koans',
    created_at: '2013-05-15T01:14:43Z',
    updated_at: '2013-05-15T01:14:43Z',
    size: 3255,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'Ruby',
    default_branch: 'master',
    gravatar_id: '',
    site_admin: false,
    owner_url: 'https://api.github.com/users/LaunchAcademy',
    owner: 'LaunchAcademy',
    owner_type: 'Organization'
  },
  {
    id: 10623528,
    name: 'issues_old',
    full_name: 'LaunchAcademy/issues_old',
    private: false,
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/LaunchAcademy/issues_old',
    created_at: '2013-06-11T14:44:23Z',
    updated_at: '2014-11-11T02:41:56Z',
    size: 176,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'Ruby',
    default_branch: 'master',
    gravatar_id: '',
    site_admin: false,
    owner_url: 'https://api.github.com/users/LaunchAcademy',
    owner: 'LaunchAcademy',
    owner_type: 'Organization'
  },
  {
    id: 10691872,
    name: 'smurf',
    full_name: 'LaunchAcademy/smurf',
    private: false,
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/LaunchAcademy/smurf',
    created_at: '2013-06-14T15:21:36Z',
    updated_at: '2014-06-12T13:35:58Z',
    size: 148,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'Ruby',
    default_branch: 'master',
    gravatar_id: '',
    site_admin: false,
    owner_url: 'https://api.github.com/users/LaunchAcademy',
    owner: 'LaunchAcademy',
    owner_type: 'Organization'
  },
  {
    id: 10821620,
    name: 'animal_design_patterns',
    full_name: 'LaunchAcademy/animal_design_patterns',
    private: false,
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/LaunchAcademy/animal_design_patterns',
    created_at: '2013-06-20T14:29:44Z',
    updated_at: '2014-06-13T02:55:48Z',
    size: 108,
    stargazers_count: 1,
    watchers_count: 1,
    language: 'Ruby',
    default_branch: 'master',
    gravatar_id: '',
    site_admin: false,
    owner_url: 'https://api.github.com/users/LaunchAcademy',
    owner: 'LaunchAcademy',
    owner_type: 'Organization'
  },
  {
    id: 10829776,
    name: 'ebert',
    full_name: 'LaunchAcademy/ebert',
    private: false,
    description: 'WIP - ruby client for the rotten tomatoes api',
    fork: false,
    url: 'https://api.github.com/repos/LaunchAcademy/ebert',
    created_at: '2013-06-20T21:22:45Z',
    updated_at: '2014-04-22T20:17:52Z',
    size: 121,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'Ruby',
    default_branch: 'master',
    gravatar_id: '',
    site_admin: false,
    owner_url: 'https://api.github.com/users/LaunchAcademy',
    owner: 'LaunchAcademy',
    owner_type: 'Organization'
  },
  {
    id: 10894620,
    name: 'last_ruby_fm',
    full_name: 'LaunchAcademy/last_ruby_fm',
    private: false,
    description: 'last_ruby_fm',
    fork: false,
    url: 'https://api.github.com/repos/LaunchAcademy/last_ruby_fm',
    created_at: '2013-06-24T00:04:12Z',
    updated_at: '2013-10-29T03:25:13Z',
    size: 108,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'Ruby',
    default_branch: 'master',
    gravatar_id: '',
    site_admin: false,
    owner_url: 'https://api.github.com/users/LaunchAcademy',
    owner: 'LaunchAcademy',
    owner_type: 'Organization'
  },
  {
    id: 11057024,
    name: 'codecabulary',
    full_name: 'LaunchAcademy/codecabulary',
    private: false,
    description: 'Launch Academy Community Resources for Learning to Code',
    fork: false,
    url: 'https://api.github.com/repos/LaunchAcademy/codecabulary',
    created_at: '2013-06-29T17:58:44Z',
    updated_at: '2016-09-28T18:50:51Z',
    size: 692,
    stargazers_count: 19,
    watchers_count: 19,
    language: 'Ruby',
    default_branch: 'master',
    gravatar_id: '',
    site_admin: false,
    owner_url: 'https://api.github.com/users/LaunchAcademy',
    owner: 'LaunchAcademy',
    owner_type: 'Organization'
  },
  {
    id: 11100178,
    name: 'weather',
    full_name: 'LaunchAcademy/weather',
    private: false,
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/LaunchAcademy/weather',
    created_at: '2013-07-01T16:06:08Z',
    updated_at: '2013-12-07T04:31:18Z',
    size: 100,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'Ruby',
    default_branch: 'master',
    gravatar_id: '',
    site_admin: false,
    owner_url: 'https://api.github.com/users/LaunchAcademy',
    owner: 'LaunchAcademy',
    owner_type: 'Organization'
  },
  {
    id: 11220480,
    name: 'konacha_example',
    full_name: 'LaunchAcademy/konacha_example',
    private: false,
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/LaunchAcademy/konacha_example',
    created_at: '2013-07-06T16:01:09Z',
    updated_at: '2013-11-05T22:53:24Z',
    size: 176,
    stargazers_count: 1,
    watchers_count: 1,
    language: 'Ruby',
    default_branch: 'master',
    gravatar_id: '',
    site_admin: false,
    owner_url: 'https://api.github.com/users/LaunchAcademy',
    owner: 'LaunchAcademy',
    owner_type: 'Organization'
  },
  {
    id: 12169439,
    name: 'first_program',
    full_name: 'LaunchAcademy/first_program',
    private: false,
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/LaunchAcademy/first_program',
    created_at: '2013-08-16T22:13:29Z',
    updated_at: '2013-10-19T19:11:48Z',
    size: 104,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'Ruby',
    default_branch: 'master',
    gravatar_id: '',
    site_admin: false,
    owner_url: 'https://api.github.com/users/LaunchAcademy',
    owner: 'LaunchAcademy',
    owner_type: 'Organization'
  },
  {
    id: 12250825,
    name: 'signatures',
    full_name: 'LaunchAcademy/signatures',
    private: false,
    description: 'Leave your mark!',
    fork: false,
    url: 'https://api.github.com/repos/LaunchAcademy/signatures',
    created_at: '2013-08-20T18:32:59Z',
    updated_at: '2014-03-05T21:13:54Z',
    size: 537,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'Ruby',
    default_branch: 'master',
    gravatar_id: '',
    site_admin: false,
    owner_url: 'https://api.github.com/users/LaunchAcademy',
    owner: 'LaunchAcademy',
    owner_type: 'Organization'
  },
  {
    id: 12299818,
    name: 'discourse',
    full_name: 'LaunchAcademy/discourse',
    private: false,
    description: 'A platform for community discussion. Free, open, simple.',
    fork: true,
    url: 'https://api.github.com/repos/LaunchAcademy/discourse',
    created_at: '2013-08-22T14:59:22Z',
    updated_at: '2014-01-03T15:50:26Z',
    size: 24844,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'Ruby',
    default_branch: 'master',
    gravatar_id: '',
    site_admin: false,
    owner_url: 'https://api.github.com/users/LaunchAcademy',
    owner: 'LaunchAcademy',
    owner_type: 'Organization'
  },
  {
    id: 12870088,
    name: 'parking',
    full_name: 'LaunchAcademy/parking',
    private: false,
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/LaunchAcademy/parking',
    created_at: '2013-09-16T14:53:57Z',
    updated_at: '2017-02-27T15:40:08Z',
    size: 59,
    stargazers_count: 1,
    watchers_count: 1,
    language: 'Ruby',
    default_branch: 'master',
    gravatar_id: '',
    site_admin: false,
    owner_url: 'https://api.github.com/users/LaunchAcademy',
    owner: 'LaunchAcademy',
    owner_type: 'Organization'
  },
  {
    id: 12914297,
    name: 'restaurant',
    full_name: 'LaunchAcademy/restaurant',
    private: false,
    description: 'What? No! You\'re in Paris now, baby! My town! No brother of mine eats rejecta-menta in my town!',
    fork: false,
    url: 'https://api.github.com/repos/LaunchAcademy/restaurant',
    created_at: '2013-09-18T04:45:56Z',
    updated_at: '2015-03-31T15:37:46Z',
    size: 158,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'Ruby',
    default_branch: 'master',
    gravatar_id: '',
    site_admin: false,
    owner_url: 'https://api.github.com/users/LaunchAcademy',
    owner: 'LaunchAcademy',
    owner_type: 'Organization'
  },
  {
    id: 13021105,
    name: 'devise_example',
    full_name: 'LaunchAcademy/devise_example',
    private: false,
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/LaunchAcademy/devise_example',
    created_at: '2013-09-22T21:11:34Z',
    updated_at: '2014-01-18T10:56:51Z',
    size: 172,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'Ruby',
    default_branch: 'master',
    gravatar_id: '',
    site_admin: false,
    owner_url: 'https://api.github.com/users/LaunchAcademy',
    owner: 'LaunchAcademy',
    owner_type: 'Organization'
  },
  {
    id: 14621316,
    name: 'sensor',
    full_name: 'LaunchAcademy/sensor',
    private: false,
    description: 'A Utility for Assembling Marketing Metrics',
    fork: false,
    url: 'https://api.github.com/repos/LaunchAcademy/sensor',
    created_at: '2013-11-22T15:33:44Z',
    updated_at: '2015-04-29T00:25:04Z',
    size: 371,
    stargazers_count: 1,
    watchers_count: 1,
    language: 'Ruby',
    default_branch: 'master',
    gravatar_id: '',
    site_admin: false,
    owner_url: 'https://api.github.com/users/LaunchAcademy',
    owner: 'LaunchAcademy',
    owner_type: 'Organization'
  },
  {
    id: 15011288,
    name: 'music',
    full_name: 'LaunchAcademy/music',
    private: false,
    description: 'Music app used for persistence challenges',
    fork: false,
    url: 'https://api.github.com/repos/LaunchAcademy/music',
    created_at: '2013-12-07T19:13:31Z',
    updated_at: '2013-12-11T03:14:06Z',
    size: 116,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'Ruby',
    default_branch: 'master',
    gravatar_id: '',
    site_admin: false,
    owner_url: 'https://api.github.com/users/LaunchAcademy',
    owner: 'LaunchAcademy',
    owner_type: 'Organization'
  },
  {
    id: 15013221,
    name: 'payroll',
    full_name: 'LaunchAcademy/payroll',
    private: false,
    description: 'Rails app to visualize employee and sales data',
    fork: false,
    url: 'https://api.github.com/repos/LaunchAcademy/payroll',
    created_at: '2013-12-07T21:30:19Z',
    updated_at: '2013-12-10T19:16:28Z',
    size: 116,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'Ruby',
    default_branch: 'master',
    gravatar_id: '',
    site_admin: false,
    owner_url: 'https://api.github.com/users/LaunchAcademy',
    owner: 'LaunchAcademy',
    owner_type: 'Organization'
  },
  {
    id: 15149254,
    name: 'secret_santa',
    full_name: 'LaunchAcademy/secret_santa',
    private: false,
    description: 'app for assigning secret santas',
    fork: false,
    url: 'https://api.github.com/repos/LaunchAcademy/secret_santa',
    created_at: '2013-12-12T22:32:11Z',
    updated_at: '2014-01-08T18:35:23Z',
    size: 184,
    stargazers_count: 1,
    watchers_count: 1,
    language: 'Ruby',
    default_branch: 'master',
    gravatar_id: '',
    site_admin: false,
    owner_url: 'https://api.github.com/users/LaunchAcademy',
    owner: 'LaunchAcademy',
    owner_type: 'Organization'
  },
  {
    id: 15151533,
    name: 'korning',
    full_name: 'LaunchAcademy/korning',
    private: false,
    description: 'Normalization Challenge',
    fork: false,
    url: 'https://api.github.com/repos/LaunchAcademy/korning',
    created_at: '2013-12-13T00:50:23Z',
    updated_at: '2014-03-18T15:10:29Z',
    size: 194,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'Ruby',
    default_branch: 'master',
    gravatar_id: '',
    site_admin: false,
    owner_url: 'https://api.github.com/users/LaunchAcademy',
    owner: 'LaunchAcademy',
    owner_type: 'Organization'
  },
  {
    id: 15193039,
    name: 'next_actions',
    full_name: 'LaunchAcademy/next_actions',
    private: false,
    description: 'Model Testing w/ Rails example',
    fork: false,
    url: 'https://api.github.com/repos/LaunchAcademy/next_actions',
    created_at: '2013-12-14T21:18:20Z',
    updated_at: '2013-12-14T21:19:33Z',
    size: 120,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'Ruby',
    default_branch: 'master',
    gravatar_id: '',
    site_admin: false,
    owner_url: 'https://api.github.com/users/LaunchAcademy',
    owner: 'LaunchAcademy',
    owner_type: 'Organization'
  },
  {
    id: 15230824,
    name: 'event_tracker',
    full_name: 'LaunchAcademy/event_tracker',
    private: false,
    description: 'exploring views rails app',
    fork: false,
    url: 'https://api.github.com/repos/LaunchAcademy/event_tracker',
    created_at: '2013-12-16T16:26:14Z',
    updated_at: '2017-04-05T17:08:31Z',
    size: 24,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'Ruby',
    default_branch: 'master',
    gravatar_id: '',
    site_admin: false,
    owner_url: 'https://api.github.com/users/LaunchAcademy',
    owner: 'LaunchAcademy',
    owner_type: 'Organization'
  },
  {
    id: 15409259,
    name: 'weQuery',
    full_name: 'LaunchAcademy/weQuery',
    private: false,
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/LaunchAcademy/weQuery',
    created_at: '2013-12-24T02:05:27Z',
    updated_at: '2014-01-11T23:23:46Z',
    size: 410,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'Ruby',
    default_branch: 'master',
    gravatar_id: '',
    site_admin: false,
    owner_url: 'https://api.github.com/users/LaunchAcademy',
    owner: 'LaunchAcademy',
    owner_type: 'Organization'
  },
  {
    id: 15513147,
    name: 'dog_park',
    full_name: 'LaunchAcademy/dog_park',
    private: false,
    description: 'Solution for Dog Park checkpoint',
    fork: false,
    url: 'https://api.github.com/repos/LaunchAcademy/dog_park',
    created_at: '2013-12-29T18:45:14Z',
    updated_at: '2013-12-31T20:44:49Z',
    size: 119,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'Ruby',
    default_branch: 'master',
    gravatar_id: '',
    site_admin: false,
    owner_url: 'https://api.github.com/users/LaunchAcademy',
    owner: 'LaunchAcademy',
    owner_type: 'Organization'
  }
]

module.exports = data
