---
title: "Ignition Foundation Tutorial"
type: "exercise"
description: "Get some practice using Foundation's grid system and other neat tools!"
tags: "foundation, css"
behaviors:

ignore:
- "ignition-foundation-tutorial.md"
