---
title: "Planet Perimeter Method"
type: "exercise"
description: "Utilize arguments and return values to represent a geometric forumula"
tags: "methods, return-values, parameters, arguments"
ignore:
- "planet-perimeter-method.md"
