---
title: "ActiveRecord Validations"
type: "article"
description: "Explore ActiveRecord Validations in the context of a Sinatra Application."
behaviors:
  - sinatra
  - sinatra_activerecord
tags: "activerecord, validations, sql"
